# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=garden.hestia
user=HestiMae
slug=powerchord
modId=powerchord
modName=PowerChord
modDescription=A component-driven RPG instrument system for hunting-horn-likes.
authors=Garden System, Sisby folk
contributors=lumiscosity, hama
license=LGPL-3.0-or-later
# Mod Version
baseVersion = 0.3.4
# Branch Metadata
branch=1.21
tagBranch=1.21
compatibleVersions=1.21.1
compatibleLoaders=fabric, quilt
